from typing import Protocol,TypedDict
9
Metadata = TypedDict('Metadata', {'filename': str, 'content_type' : str, 'size' : int})

class StorageBackend(Protocol):
    async def create(self,document_id: str, document: bytes) -> str : ...
    async def read(self, document_id: str) -> bytes : ...
    async def exists(self,document_id: str) -> bool : ...
    async def delete(self,document_id: str) -> None : ...

class DocStore(Protocol):
    async def create(self,document_id: str, metadata: Metadata) -> None : ...
    async def read_by_id(self, document_id : str) -> dict | None : ...
    async def read(self) -> list[dict] : ...
    async def delete(self,document_id: str) -> None : ...